/**
 * Mermaid SVG Detector
 * Handles SVGs generated by Mermaid.js (flowcharts, sequence diagrams, etc.)
 */

export default {
  name: 'mermaid',
  priority: 10,

  /**
   * Check if this SVG appears to be Mermaid output
   */
  canHandle(svg) {
    // Mermaid flowcharts have nodes with id="flowchart-X-N"
    if (svg.querySelector('g.node[id^="flowchart-"]')) return true;
    // Mermaid also adds a .mermaid class sometimes
    if (svg.querySelector('.mermaid')) return true;
    // Check for mermaid edge patterns
    if (svg.querySelector('[id^="L_"]')) return true;
    return false;
  },

  /**
   * Detect all animatable elements in a Mermaid SVG
   */
  detect(svg, ctx) {
    const elements = [];
    const seenIds = new Set();

    // === NODES ===
    // Mermaid nodes: <g class="node ..." id="flowchart-A-0">
    svg.querySelectorAll('g.node[id^="flowchart-"]').forEach(el => {
      if (ctx.isInDefs(el)) return;

      const rect = el.getBoundingClientRect();
      if (rect.width < 10 || rect.height < 10) return;

      // Extract node name from ID: "flowchart-A-0" → "A"
      const parts = el.id.split('-');
      const id = parts.length >= 2 ? parts[1] : el.id;

      if (seenIds.has(id)) return;
      seenIds.add(id);

      elements.push({
        id,
        element: el,
        bounds: ctx.toViewBox(rect),
        type: 'node'
      });
    });

    // === EDGES ===
    // Mermaid edges: elements with id like "L_A_B_0"
    svg.querySelectorAll('[id^="L_"]').forEach(el => {
      if (ctx.isInDefs(el)) return;

      const rect = el.getBoundingClientRect();
      if (rect.width < 5 && rect.height < 5) return;

      // Extract edge info from ID: "L_A_B_0" → "A→B"
      const parts = el.id.split('_');
      if (parts.length < 3) return;

      const id = `${parts[1]}→${parts[2]}`;

      // Skip duplicates (Mermaid creates multiple elements with same ID pattern)
      if (seenIds.has(id)) return;
      seenIds.add(id);

      elements.push({
        id,
        element: el,
        bounds: ctx.toViewBox(rect),
        type: 'edge'
      });
    });

    return elements;
  }
};
