/**
 * Mermaid SVG Detector
 * Handles SVGs generated by Mermaid.js (flowcharts, sequence diagrams, etc.)
 */

export default {
  name: 'mermaid',
  priority: 10,

  /**
   * Check if this SVG appears to be Mermaid output
   */
  canHandle(svg) {
    // Mermaid flowcharts have nodes with id="flowchart-X-N"
    if (svg.querySelector('g.node[id^="flowchart-"]')) return true;
    // Mermaid also adds a .mermaid class sometimes
    if (svg.querySelector('.mermaid')) return true;
    // Check for mermaid edge patterns
    if (svg.querySelector('[id^="L_"]')) return true;
    return false;
  },

  /**
   * Detect all animatable elements in a Mermaid SVG
   */
  detect(svg, ctx) {
    const elements = [];
    const seenIds = new Set();

    // === NODES ===
    // Mermaid nodes: <g class="node ..." id="flowchart-A-0">
    svg.querySelectorAll('g.node[id^="flowchart-"]').forEach(el => {
      if (ctx.isInDefs(el)) return;

      const rect = el.getBoundingClientRect();
      if (rect.width < 10 || rect.height < 10) return;

      // Extract node name from ID: "flowchart-my-node-0" -> "my-node"
      // Mermaid ids are "flowchart-<node-name>-<counter>"; the node name
      // itself can contain dashes, so split-by-index truncates it.
      const nodeMatch = el.id.match(/^flowchart-(.+)-\d+$/);
      const id = nodeMatch ? nodeMatch[1] : el.id;

      if (seenIds.has(id)) return;
      seenIds.add(id);

      elements.push({
        id,
        element: el,
        bounds: ctx.toViewBox(rect),
        type: 'node'
      });
    });

    // === EDGES ===
    // Mermaid edges: elements with id like "L_A_B_0"
    svg.querySelectorAll('[id^="L_"]').forEach(el => {
      if (ctx.isInDefs(el)) return;

      const rect = el.getBoundingClientRect();
      if (rect.width < 5 && rect.height < 5) return;

      // Mermaid edge ids look like "L_A_B_0" ("L_<source>_<target>_<counter>"),
      // but node names can themselves contain underscores, so splitting on
      // "_" can't reliably recover source/target. Only the trailing counter
      // is unambiguous. Use the raw id (always unique per SVG, including for
      // parallel edges like "L_A_B_0"/"L_A_B_1") as the dedup key and id, and
      // derive a best-effort friendlier label for display only.
      if (seenIds.has(el.id)) return;
      seenIds.add(el.id);

      const edgeMatch = el.id.match(/^L_(.+)_(\d+)$/);
      const label = edgeMatch ? edgeMatch[1].replace(/_/g, '→') : el.id;

      elements.push({
        id: el.id,
        label,
        element: el,
        bounds: ctx.toViewBox(rect),
        type: 'edge'
      });
    });

    return elements;
  }
};
